# Returns a list of all profiles
GET http://localhost:8000/profiles/

######

# Creates a new profile
POST http://localhost:8000/profiles/
Content-Type: application/json

{
    "login": "login_4",
    "password": "password_4",
    "first_name": "Harry",
    "last_name": "Oldman",
    "city": "Texas",
    "bio": "I'm a lawyer"

}

######

# Modifies an existing profile
PUT http://localhost:8000/profiles/3/
Content-Type: application/json
Authorization: Token 071a086a36b4789d23debae24214ff358fb8e775

{
    "login": "login_3",
    "password": "password_3",
    "bio": "Looking for a job"
}

######

# Removes an existing profile
DELETE http://localhost:8000/profiles/3/
Authorization: Token 18adce330e70f32a937e8963379b7cf98f33d886

######

# Search a profile by id
GET http://localhost:8000/profiles/3/

#####

# Filter by multiple fields
GET http://localhost:8000/profiles/?first_name=Harry&city=Texas