# Returns a list of all profiles
GET http://localhost:8000/profiles/

######

# Creates a new profile
POST http://localhost:8000/profiles/
Content-Type: application/json

{
    "login": "login_3",
    "password": "password_3",
    "bio": "I'm from Togliatti"

}

######

# Modifies an existing profile
PUT http://localhost:8000/profiles/4/
Content-Type: application/json
Authorization: Token 6fc50e476585a0c58b8ce9c9650067b1362ebc23

{
    "bio": "It's me!"
}

######

# Removes an existing profile
DELETE http://localhost:8000/profiles/6/
Authorization: Token 206365bc097ff0a04b64e62e4c9d062551eb7091

######

# Search a profile by id
GET http://localhost:8000/profiles/9/
